exchange:
  name: 'binance'
  api_key: '${BINANCE_API_KEY}'
  api_secret: '${BINANCE_API_SECRET}'
  default_symbol: 'BTC/USDT'
  timeframe: '1h'

backtest:
  initial_capital: 10000.0
  start_date: '2024-01-01T00:00:00Z'
  simultaniouseous_trades: 4

live:
  initial_capital: 1000.0

strategies:
  advanced_ema_strategy:
    enabled: true
    ema_fast: 50
    ema_slow: 200
    rsi_period: 14
    rsi_oversold: 30
    rsi_overbought: 70
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
    atr_period: 14
    atr_multiplier: 2.0
    volume_threshold: 1.2  # Volumen debe ser 20% mayor que promedio
    volume_lookback: 20    # Períodos para calcular volumen promedio
    avoid_weekends: true
  ema_cross:
    enabled: false
    ema_short: 20
    ema_long: 50
  ema_cross_rsi_macd:
    enabled: false
    ema_short: 9
    ema_long: 21
    rsi_period: 14
    rsi_sensitivity: 8
    rsi_overbought: 70
    rsi_oversold: 30
    macd_fast: 12
    macd_slow: 26
    macd_signal: 9
  ema_rebound:
    enabled: false
    ema_period: 200
  bollinger_bands_breakout:
    enabled: false
    bb_period: 20
    bb_std_dev: 2

risk_management:
  risk_per_trade: 0.02
  use_dynamic_tp: true
  use_dynamic_sl: false
  static_take_profit_percentage: 0.1
  static_stop_loss_percentage: 0.05

persistence:
  trades_file: 'trades.csv'
  log_file: 'bot.log'
  metrics_file: 'metrics.csv'
