version: '3.8'

services:
  trading-bot:
    build: .
    container_name: trading_bot
    volumes:
      - .:/app
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    command: ["python", "main.py", "--mode", "backtest"]
